# Generated by Django 2.2.15 on 2025-02-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_conversation_per_ad',
        ),
    ]
