# Generated by Django 2.2.15 on 2025-02-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20250205_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.County'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Buses & Microbuses', 'Buses & Microbuses'), ('Heavy Equipment', 'Heavy Equipment'), ('Motorcycles', 'Motorcycles'), ('Trucks', 'Trucks'), ('Other Vehicles', 'Other Vehicles'), ('New Builds', 'New Builds'), ('Houses & Apartments for Rent', 'Houses & Apartments for Rent'), ('Houses & Apartments for Sale', 'Houses & Apartments for Sale'), ('Land for Sale', 'Land for Sale'), ('Commercial Property', 'Commercial Property'), ('Other Property', 'Other Property'), ('Phones', 'Phones'), ('Laptops', 'Laptops'), ('Desktops', 'Desktops'), ('Tablets', 'Tablets'), ('Televisions', 'Televisions'), ('Other Electronics', 'Other Electronics'), ("Men's Fashion", "Men's Fashion"), ("Women's Fashion", "Women's Fashion"), ("Kids' Fashion", "Kids' Fashion"), ('Other Fashion', 'Other Fashion'), ('Furniture', 'Furniture'), ('Appliances', 'Appliances'), ('Home Decor', 'Home Decor'), ('Office Equipment', 'Office Equipment'), ('Other Home & Office', 'Other Home & Office'), ('Jobs', 'Jobs'), ('Services', 'Services'), ('Livestock', 'Livestock'), ('Farming Equipment', 'Farming Equipment'), ('Other Agriculture', 'Other Agriculture'), ('Fitness', 'Fitness'), ('Sports Equipment', 'Sports Equipment'), ('Other Sports & Outdoors', 'Other Sports & Outdoors'), ('Food', 'Food'), ('Beverages', 'Beverages'), ('Health', 'Health'), ('Beauty', 'Beauty'), ('Other', 'Other'), ('Adult Products', 'Adult Products'), ('Intimacy & Relationships', 'Intimacy & Relationships')], default='Other', max_length=50),
        ),
    ]
