# Generated by Django 2.2.15 on 2025-01-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_auto_20250129_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsbottombanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bottom Banner', 'verbose_name_plural': 'Bottom Banners'},
        ),
        migrations.AlterModelOptions(
            name='adsrightbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Right Banner', 'verbose_name_plural': 'Right Banners'},
        ),
        migrations.AlterModelOptions(
            name='adstopbanner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Top Banner', 'verbose_name_plural': 'Top Banners'},
        ),
        migrations.RemoveField(
            model_name='adsbottombanner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adsrightbanner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='adstopbanner',
            name='is_active',
        ),
    ]
