# Generated by Django 2.2.15 on 2025-01-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_auto_20250130_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='county_name',
            field=models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita-Taveta'), ('Nairobi', 'Nairobi'), ('Kiambu', 'Kiambu'), ('Muranga', 'Muranga'), ('Kirinyaga', 'Kirinyaga'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Nakuru', 'Nakuru'), ('Laikipia', 'Laikipia'), ('Samburu', 'Samburu'), ('Trans-Nzoia', 'Trans-Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo-Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Siaya', 'Siaya'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Turkana', 'Turkana'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=100, unique=True),
        ),
    ]
